# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beneficios.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rango_exceso = QtWidgets.QSpinBox(self.groupBox)
        self.rango_exceso.setObjectName("rango_exceso")
        self.gridLayout.addWidget(self.rango_exceso, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.valor_h_extra = QtWidgets.QSpinBox(self.groupBox)
        self.valor_h_extra.setObjectName("valor_h_extra")
        self.gridLayout.addWidget(self.valor_h_extra, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.valor_he_exceso = QtWidgets.QSpinBox(self.groupBox)
        self.valor_he_exceso.setMaximum(999)
        self.valor_he_exceso.setObjectName("valor_he_exceso")
        self.gridLayout.addWidget(self.valor_he_exceso, 3, 0, 1, 1)
        self.info_he = QtWidgets.QPlainTextEdit(self.groupBox)
        self.info_he.setObjectName("info_he")
        self.gridLayout.addWidget(self.info_he, 3, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 1, 1, 1)
        self.info_hora_nocturna = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.info_hora_nocturna.setObjectName("info_hora_nocturna")
        self.gridLayout_2.addWidget(self.info_hora_nocturna, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.valor_h_nocturna = QtWidgets.QSpinBox(self.groupBox_2)
        self.valor_h_nocturna.setMaximum(999)
        self.valor_h_nocturna.setObjectName("valor_h_nocturna")
        self.gridLayout_2.addWidget(self.valor_h_nocturna, 1, 0, 1, 1)
        self.fin_h_nocturna = QtWidgets.QTimeEdit(self.groupBox_2)
        self.fin_h_nocturna.setObjectName("fin_h_nocturna")
        self.gridLayout_2.addWidget(self.fin_h_nocturna, 3, 1, 1, 1)
        self.inicio_h_nocturna = QtWidgets.QTimeEdit(self.groupBox_2)
        self.inicio_h_nocturna.setObjectName("inicio_h_nocturna")
        self.gridLayout_2.addWidget(self.inicio_h_nocturna, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.valor_trab_descanso = QtWidgets.QSpinBox(self.groupBox_3)
        self.valor_trab_descanso.setMaximum(300)
        self.valor_trab_descanso.setObjectName("valor_trab_descanso")
        self.gridLayout_3.addWidget(self.valor_trab_descanso, 1, 0, 1, 1)
        self.info_trab_descanso = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.info_trab_descanso.setObjectName("info_trab_descanso")
        self.gridLayout_3.addWidget(self.info_trab_descanso, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dias_por_mes = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dias_por_mes.setObjectName("dias_por_mes")
        self.gridLayout_4.addWidget(self.dias_por_mes, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.info_dias_mes = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.info_dias_mes.setObjectName("info_dias_mes")
        self.gridLayout_4.addWidget(self.info_dias_mes, 1, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_4)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horas_por_dia = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.horas_por_dia.setObjectName("horas_por_dia")
        self.gridLayout_7.addWidget(self.horas_por_dia, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 1, 1, 1)
        self.info_horas_dia = QtWidgets.QTextEdit(self.groupBox_5)
        self.info_horas_dia.setObjectName("info_horas_dia")
        self.gridLayout_7.addWidget(self.info_horas_dia, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_7)
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        self.verticalLayout.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.guardar = QtWidgets.QPushButton(self.frame_3)
        self.guardar.setObjectName("guardar")
        self.horizontalLayout_3.addWidget(self.guardar)
        spacerItem1 = QtWidgets.QSpacerItem(103, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cancelar = QtWidgets.QPushButton(self.frame_3)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout_3.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beneficios según ley"))
        self.groupBox.setTitle(_translate("MainWindow", "Horas extraordinarias:"))
        self.label.setText(_translate("MainWindow", "Valor Hora Extra (%):"))
        self.label_2.setText(_translate("MainWindow", "Rango de exceso HE(horas):"))
        self.label_3.setText(_translate("MainWindow", "Valor Horas Extra Exceso (%):"))
        self.label_4.setText(_translate("MainWindow", "Info hora extra:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Horas nocturnas:"))
        self.label_5.setText(_translate("MainWindow", "Valor hora nocturna (%):"))
        self.label_8.setText(_translate("MainWindow", "Hora Nocturna fin:"))
        self.label_7.setText(_translate("MainWindow", "Hora Nocturna Inicio:"))
        self.fin_h_nocturna.setDisplayFormat(_translate("MainWindow", "hh:mm"))
        self.inicio_h_nocturna.setDisplayFormat(_translate("MainWindow", "hh:mm"))
        self.label_6.setText(_translate("MainWindow", "Info Hora nocturna:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Trabajo en descanso:"))
        self.label_10.setText(_translate("MainWindow", "Info trabajo en descanso:"))
        self.label_9.setText(_translate("MainWindow", "Valor trabajo en descanso (%):"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Días laborables:"))
        self.label_11.setText(_translate("MainWindow", "Info días laborables:"))
        self.label_12.setText(_translate("MainWindow", "Días laborables por mes:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Horas por día:"))
        self.label_13.setText(_translate("MainWindow", "Horas por día"))
        self.label_14.setText(_translate("MainWindow", "Info horas por día"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


