# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'correo.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem1 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.correo_conectado = QtWidgets.QLineEdit(self.centralwidget)
        self.correo_conectado.setReadOnly(True)
        self.correo_conectado.setObjectName("correo_conectado")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.correo_conectado)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fecha_conexion = QtWidgets.QLineEdit(self.centralwidget)
        self.fecha_conexion.setReadOnly(True)
        self.fecha_conexion.setObjectName("fecha_conexion")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fecha_conexion)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.conectar = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conectar.sizePolicy().hasHeightForWidth())
        self.conectar.setSizePolicy(sizePolicy)
        self.conectar.setObjectName("conectar")
        self.horizontalLayout_3.addWidget(self.conectar)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cambiar = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cambiar.sizePolicy().hasHeightForWidth())
        self.cambiar.setSizePolicy(sizePolicy)
        self.cambiar.setObjectName("cambiar")
        self.horizontalLayout_3.addWidget(self.cambiar)
        spacerItem4 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.groupBox_mensaje_prueba = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_mensaje_prueba.setObjectName("groupBox_mensaje_prueba")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_mensaje_prueba)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_mensaje_prueba)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dir_correo_prueba = QtWidgets.QLineEdit(self.groupBox_mensaje_prueba)
        self.dir_correo_prueba.setObjectName("dir_correo_prueba")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dir_correo_prueba)
        self.label_4 = QtWidgets.QLabel(self.groupBox_mensaje_prueba)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.titulo = QtWidgets.QLineEdit(self.groupBox_mensaje_prueba)
        self.titulo.setObjectName("titulo")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.titulo)
        self.label_5 = QtWidgets.QLabel(self.groupBox_mensaje_prueba)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.mensaje = QtWidgets.QLineEdit(self.groupBox_mensaje_prueba)
        self.mensaje.setObjectName("mensaje")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mensaje)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.enviar_correo = QtWidgets.QPushButton(self.groupBox_mensaje_prueba)
        self.enviar_correo.setObjectName("enviar_correo")
        self.verticalLayout.addWidget(self.enviar_correo)
        self.verticalLayout_2.addWidget(self.groupBox_mensaje_prueba)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 347, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Configuración de correo"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Se debe poseer un correo de gmail para poder enviar por correo los recibos de pago de los trabajadores. Se recomienda que cree un correo nuevo que solo se use para tal fin. Luego, debe conectar dicho correo Gmail a la aplicación SNPDO pulsando el botón conectar. Después, envíe un mensaje de prueba para verificar que el programa quedó configurado correctamente.</span></p></body></html>"))
        self.cancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cierra la ventana actual.</p></body></html>"))
        self.cancelar.setText(_translate("MainWindow", "Cerrar"))
        self.label.setText(_translate("MainWindow", "Correo conectado:"))
        self.correo_conectado.setToolTip(_translate("MainWindow", "<html><head/><body><p>Muestra el correo de Gmail que está actualmente conectado a la aplicación.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Fecha de conexión:"))
        self.fecha_conexion.setToolTip(_translate("MainWindow", "<html><head/><body><p>Muestra la fecha cuando se hizo la conexión del correo mostrado arriba de esta línea.</p></body></html>"))
        self.conectar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presione aquí para iniciar el proceso de conexión de una cuenta Gmail</p></body></html>"))
        self.conectar.setText(_translate("MainWindow", "Conectar Cuenta"))
        self.cambiar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presione aquí para cambiar el correo desde donde se enviaran los recibos de nómina.</p></body></html>"))
        self.cambiar.setText(_translate("MainWindow", "Cambiar Cuenta"))
        self.groupBox_mensaje_prueba.setTitle(_translate("MainWindow", "Mensaje de prueba:"))
        self.label_3.setText(_translate("MainWindow", "Correo:"))
        self.label_4.setText(_translate("MainWindow", "Titulo:"))
        self.label_5.setText(_translate("MainWindow", "Mensaje:"))
        self.enviar_correo.setText(_translate("MainWindow", "Enviar correo de prueba"))


