# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diaNoLaborables.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiasNoLaborables(object):
    def setupUi(self, DiasNoLaborables):
        DiasNoLaborables.setObjectName("DiasNoLaborables")
        DiasNoLaborables.setWindowModality(QtCore.Qt.WindowModal)
        DiasNoLaborables.resize(358, 292)
        self.centralwidget = QtWidgets.QWidget(DiasNoLaborables)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout.addWidget(self.tableWidget)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout.addWidget(self.agregar)
        spacerItem1 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.borrar = QtWidgets.QPushButton(self.frame)
        self.borrar.setObjectName("borrar")
        self.horizontalLayout.addWidget(self.borrar)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame)
        DiasNoLaborables.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DiasNoLaborables)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 18))
        self.menubar.setObjectName("menubar")
        DiasNoLaborables.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DiasNoLaborables)
        self.statusbar.setObjectName("statusbar")
        DiasNoLaborables.setStatusBar(self.statusbar)

        self.retranslateUi(DiasNoLaborables)
        QtCore.QMetaObject.connectSlotsByName(DiasNoLaborables)

    def retranslateUi(self, DiasNoLaborables):
        _translate = QtCore.QCoreApplication.translate
        DiasNoLaborables.setWindowTitle(_translate("DiasNoLaborables", "Días no laborables"))
        self.tableWidget.setToolTip(_translate("DiasNoLaborables", "<html><head/><body><p>Los días no laborables son publicados anualmente en el mes de diciembre en la página web del Ministerio del Trabajo.</p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DiasNoLaborables", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DiasNoLaborables", "Descripción"))
        self.label_3.setText(_translate("DiasNoLaborables", "Agregar nueva fecha:"))
        self.label_2.setText(_translate("DiasNoLaborables", "Descripción:"))
        self.label.setText(_translate("DiasNoLaborables", "Fecha:"))
        self.dateEdit.setToolTip(_translate("DiasNoLaborables", "<html><head/><body><p>Colocar fecha del día feriado.</p></body></html>"))
        self.dateEdit.setDisplayFormat(_translate("DiasNoLaborables", "dd-MM-yyyy"))
        self.lineEdit.setToolTip(_translate("DiasNoLaborables", "<html><head/><body><p>Colocar el motivo del día feriado. Por ejemplo, &quot;Año nuevo&quot;.</p></body></html>"))
        self.agregar.setToolTip(_translate("DiasNoLaborables", "<html><head/><body><p>Al presionar este botón se agregarán la fecha a la base de datos.</p></body></html>"))
        self.agregar.setText(_translate("DiasNoLaborables", "Agregar"))
        self.cancelar.setToolTip(_translate("DiasNoLaborables", "<html><head/><body><p>Al presionar este botón se cierra la ventana sin cambiar nada.</p></body></html>"))
        self.cancelar.setText(_translate("DiasNoLaborables", "Cerrar"))
        self.borrar.setToolTip(_translate("DiasNoLaborables", "<html><head/><body><p>Si desea borrar alguna fecha, debe seleccionarla primero y luego presionar este botón.</p></body></html>"))
        self.borrar.setText(_translate("DiasNoLaborables", "Borrar"))
