# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dotacion.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(247, 178)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.trabajador = QtWidgets.QComboBox(self.groupBox_8)
        self.trabajador.setObjectName("trabajador")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trabajador)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 0, 0, 1, 1)
        self.cant_pant = QtWidgets.QSpinBox(self.groupBox_8)
        self.cant_pant.setObjectName("cant_pant")
        self.gridLayout_7.addWidget(self.cant_pant, 0, 3, 1, 1)
        self.cant_camisa = QtWidgets.QSpinBox(self.groupBox_8)
        self.cant_camisa.setObjectName("cant_camisa")
        self.gridLayout_7.addWidget(self.cant_camisa, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_8)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 0, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_8)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 0, 6, 1, 1)
        self.cant_lentes = QtWidgets.QSpinBox(self.groupBox_8)
        self.cant_lentes.setObjectName("cant_lentes")
        self.gridLayout_7.addWidget(self.cant_lentes, 0, 7, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_8)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 1, 0, 1, 1)
        self.cant_guantes = QtWidgets.QSpinBox(self.groupBox_8)
        self.cant_guantes.setObjectName("cant_guantes")
        self.gridLayout_7.addWidget(self.cant_guantes, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_8)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 1, 2, 1, 1)
        self.cant_zapatos = QtWidgets.QSpinBox(self.groupBox_8)
        self.cant_zapatos.setObjectName("cant_zapatos")
        self.gridLayout_7.addWidget(self.cant_zapatos, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_48 = QtWidgets.QLabel(self.groupBox_8)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_5.addWidget(self.label_48)
        self.nota_dota = QtWidgets.QLineEdit(self.groupBox_8)
        self.nota_dota.setObjectName("nota_dota")
        self.horizontalLayout_5.addWidget(self.nota_dota)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.crear = QtWidgets.QPushButton(self.frame)
        self.crear.setObjectName("crear")
        self.horizontalLayout.addWidget(self.crear)
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.trabajador, self.cant_camisa)
        MainWindow.setTabOrder(self.cant_camisa, self.cant_pant)
        MainWindow.setTabOrder(self.cant_pant, self.cant_lentes)
        MainWindow.setTabOrder(self.cant_lentes, self.cant_guantes)
        MainWindow.setTabOrder(self.cant_guantes, self.cant_zapatos)
        MainWindow.setTabOrder(self.cant_zapatos, self.nota_dota)
        MainWindow.setTabOrder(self.nota_dota, self.crear)
        MainWindow.setTabOrder(self.crear, self.cancelar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dotación a trabajador"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Dotar a trabajador"))
        self.label.setText(_translate("MainWindow", "Trabajador:"))
        self.label_25.setText(_translate("MainWindow", "Camisas:"))
        self.label_36.setText(_translate("MainWindow", "Pantalones:"))
        self.label_38.setText(_translate("MainWindow", "Lentes:"))
        self.label_39.setText(_translate("MainWindow", "Guantes:"))
        self.label_37.setText(_translate("MainWindow", "Zapatos:"))
        self.label_48.setText(_translate("MainWindow", "Nota:"))
        self.crear.setText(_translate("MainWindow", "Crear"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))
