# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'horas_extra.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.fecha_doc = QtWidgets.QDateEdit(self.frame_2)
        self.fecha_doc.setReadOnly(True)
        self.fecha_doc.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fecha_doc.setObjectName("fecha_doc")
        self.horizontalLayout_2.addWidget(self.fecha_doc)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.id_h_visible = QtWidgets.QLineEdit(self.frame_2)
        self.id_h_visible.setMaximumSize(QtCore.QSize(50, 16777215))
        self.id_h_visible.setMaxLength(100)
        self.id_h_visible.setObjectName("id_h_visible")
        self.horizontalLayout_2.addWidget(self.id_h_visible)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.trabajador = QtWidgets.QComboBox(self.groupBox)
        self.trabajador.setObjectName("trabajador")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trabajador)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.tipohoraextra = QtWidgets.QComboBox(self.groupBox)
        self.tipohoraextra.setObjectName("tipohoraextra")
        self.tipohoraextra.addItem("")
        self.tipohoraextra.addItem("")
        self.tipohoraextra.addItem("")
        self.tipohoraextra.addItem("")
        self.tipohoraextra.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tipohoraextra)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fecha = QtWidgets.QDateEdit(self.groupBox)
        self.fecha.setCalendarPopup(True)
        self.fecha.setObjectName("fecha")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fecha)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hora_i = QtWidgets.QTimeEdit(self.groupBox)
        self.hora_i.setCalendarPopup(False)
        self.hora_i.setObjectName("hora_i")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.hora_i)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.hora_f = QtWidgets.QTimeEdit(self.groupBox)
        self.hora_f.setObjectName("hora_f")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.hora_f)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.nota = QtWidgets.QLineEdit(self.groupBox)
        self.nota.setObjectName("nota")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.nota)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.salario_mensual = QtWidgets.QLineEdit(self.groupBox)
        self.salario_mensual.setReadOnly(True)
        self.salario_mensual.setObjectName("salario_mensual")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.salario_mensual)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.salario_hora = QtWidgets.QLineEdit(self.groupBox)
        self.salario_hora.setReadOnly(True)
        self.salario_hora.setObjectName("salario_hora")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.salario_hora)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.trabajo_en_descanso = QtWidgets.QCheckBox(self.groupBox_2)
        self.trabajo_en_descanso.setObjectName("trabajo_en_descanso")
        self.verticalLayout_2.addWidget(self.trabajo_en_descanso)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.hora_extra_noct = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hora_extra_noct.sizePolicy().hasHeightForWidth())
        self.hora_extra_noct.setSizePolicy(sizePolicy)
        self.hora_extra_noct.setReadOnly(True)
        self.hora_extra_noct.setObjectName("hora_extra_noct")
        self.gridLayout_2.addWidget(self.hora_extra_noct, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 4, 1, 1)
        self.total_he_doble_exceso = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_he_doble_exceso.sizePolicy().hasHeightForWidth())
        self.total_he_doble_exceso.setSizePolicy(sizePolicy)
        self.total_he_doble_exceso.setReadOnly(True)
        self.total_he_doble_exceso.setMaximum(9999999.99)
        self.total_he_doble_exceso.setObjectName("total_he_doble_exceso")
        self.gridLayout_2.addWidget(self.total_he_doble_exceso, 1, 5, 1, 1)
        self.total_he_normal = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_he_normal.sizePolicy().hasHeightForWidth())
        self.total_he_normal.setSizePolicy(sizePolicy)
        self.total_he_normal.setReadOnly(True)
        self.total_he_normal.setMaximum(9999999.99)
        self.total_he_normal.setObjectName("total_he_normal")
        self.gridLayout_2.addWidget(self.total_he_normal, 0, 5, 1, 1)
        self.hora_extra = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hora_extra.sizePolicy().hasHeightForWidth())
        self.hora_extra.setSizePolicy(sizePolicy)
        self.hora_extra.setReadOnly(True)
        self.hora_extra.setObjectName("hora_extra")
        self.gridLayout_2.addWidget(self.hora_extra, 0, 1, 1, 1)
        self.hora_extra_doble = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hora_extra_doble.sizePolicy().hasHeightForWidth())
        self.hora_extra_doble.setSizePolicy(sizePolicy)
        self.hora_extra_doble.setReadOnly(True)
        self.hora_extra_doble.setObjectName("hora_extra_doble")
        self.gridLayout_2.addWidget(self.hora_extra_doble, 1, 1, 1, 1)
        self.gran_total = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gran_total.sizePolicy().hasHeightForWidth())
        self.gran_total.setSizePolicy(sizePolicy)
        self.gran_total.setReadOnly(True)
        self.gran_total.setMaximum(9999999.99)
        self.gran_total.setObjectName("gran_total")
        self.gridLayout_2.addWidget(self.gran_total, 3, 5, 1, 1)
        self.total_he_nocturno = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_he_nocturno.sizePolicy().hasHeightForWidth())
        self.total_he_nocturno.setSizePolicy(sizePolicy)
        self.total_he_nocturno.setReadOnly(True)
        self.total_he_nocturno.setPrefix("")
        self.total_he_nocturno.setMaximum(9999999.99)
        self.total_he_nocturno.setObjectName("total_he_nocturno")
        self.gridLayout_2.addWidget(self.total_he_nocturno, 2, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)
        self.porc_hora_extra = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.porc_hora_extra.sizePolicy().hasHeightForWidth())
        self.porc_hora_extra.setSizePolicy(sizePolicy)
        self.porc_hora_extra.setReadOnly(True)
        self.porc_hora_extra.setObjectName("porc_hora_extra")
        self.gridLayout_2.addWidget(self.porc_hora_extra, 0, 3, 1, 1)
        self.porc_hora_extra_exceso = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.porc_hora_extra_exceso.sizePolicy().hasHeightForWidth())
        self.porc_hora_extra_exceso.setSizePolicy(sizePolicy)
        self.porc_hora_extra_exceso.setReadOnly(True)
        self.porc_hora_extra_exceso.setObjectName("porc_hora_extra_exceso")
        self.gridLayout_2.addWidget(self.porc_hora_extra_exceso, 1, 3, 1, 1)
        self.porc_nocturno = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.porc_nocturno.sizePolicy().hasHeightForWidth())
        self.porc_nocturno.setSizePolicy(sizePolicy)
        self.porc_nocturno.setReadOnly(True)
        self.porc_nocturno.setObjectName("porc_nocturno")
        self.gridLayout_2.addWidget(self.porc_nocturno, 2, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.borrar = QtWidgets.QPushButton(self.frame)
        self.borrar.setObjectName("borrar")
        self.horizontalLayout.addWidget(self.borrar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout.addWidget(self.agregar)
        spacerItem3 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fecha_doc, self.id_h_visible)
        MainWindow.setTabOrder(self.id_h_visible, self.trabajador)
        MainWindow.setTabOrder(self.trabajador, self.salario_mensual)
        MainWindow.setTabOrder(self.salario_mensual, self.salario_hora)
        MainWindow.setTabOrder(self.salario_hora, self.tipohoraextra)
        MainWindow.setTabOrder(self.tipohoraextra, self.fecha)
        MainWindow.setTabOrder(self.fecha, self.hora_i)
        MainWindow.setTabOrder(self.hora_i, self.hora_f)
        MainWindow.setTabOrder(self.hora_f, self.nota)
        MainWindow.setTabOrder(self.nota, self.trabajo_en_descanso)
        MainWindow.setTabOrder(self.trabajo_en_descanso, self.hora_extra)
        MainWindow.setTabOrder(self.hora_extra, self.hora_extra_doble)
        MainWindow.setTabOrder(self.hora_extra_doble, self.hora_extra_noct)
        MainWindow.setTabOrder(self.hora_extra_noct, self.porc_hora_extra)
        MainWindow.setTabOrder(self.porc_hora_extra, self.porc_hora_extra_exceso)
        MainWindow.setTabOrder(self.porc_hora_extra_exceso, self.porc_nocturno)
        MainWindow.setTabOrder(self.porc_nocturno, self.total_he_normal)
        MainWindow.setTabOrder(self.total_he_normal, self.total_he_doble_exceso)
        MainWindow.setTabOrder(self.total_he_doble_exceso, self.total_he_nocturno)
        MainWindow.setTabOrder(self.total_he_nocturno, self.gran_total)
        MainWindow.setTabOrder(self.gran_total, self.borrar)
        MainWindow.setTabOrder(self.borrar, self.agregar)
        MainWindow.setTabOrder(self.agregar, self.cancelar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro de horas extras"))
        self.label_20.setText(_translate("MainWindow", "Fecha de documento:"))
        self.fecha_doc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Fecha en la que se hace el registro.</p></body></html>"))
        self.fecha_doc.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.label_19.setText(_translate("MainWindow", "ID:"))
        self.id_h_visible.setToolTip(_translate("MainWindow", "<html><head/><body><p>ID del registro.</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Registro de horas extraordinarias:"))
        self.label.setText(_translate("MainWindow", "Trabajador:"))
        self.trabajador.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione de este listado al trabajador que le quiera registrar la variación</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Tipo de hora extra:"))
        self.tipohoraextra.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione el motivo que indica el código del trabajo que justifique el trabajo extra.</p></body></html>"))
        self.tipohoraextra.setItemText(0, _translate("MainWindow", "a)accidentes"))
        self.tipohoraextra.setItemText(1, _translate("MainWindow", "b)trabajos imprescindibles"))
        self.tipohoraextra.setItemText(2, _translate("MainWindow", "c)salvar materia prima"))
        self.tipohoraextra.setItemText(3, _translate("MainWindow", "d)fuerza mayor"))
        self.tipohoraextra.setItemText(4, _translate("MainWindow", "e)Exceso de pedidos"))
        self.label_3.setText(_translate("MainWindow", "Fecha de ocurrencia:"))
        self.fecha.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione la fecha donde ocurrio la variación.</p></body></html>"))
        self.fecha.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.label_4.setText(_translate("MainWindow", "Hora inicial:"))
        self.hora_i.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coloque la hora inicial de la variación. Hora militar.</p></body></html>"))
        self.hora_i.setDisplayFormat(_translate("MainWindow", "hh:mm"))
        self.label_5.setText(_translate("MainWindow", "Hora final:"))
        self.hora_f.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coloque la hora final de la variación. Hora militar.</p></body></html>"))
        self.hora_f.setDisplayFormat(_translate("MainWindow", "hh:mm"))
        self.label_6.setText(_translate("MainWindow", "Nota:"))
        self.nota.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coloque una nota. Es un campo obligatorio, si no coloca información, no podrá crear la variación</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Salario mensual:"))
        self.salario_mensual.setToolTip(_translate("MainWindow", "<html><head/><body><p>Muestra el salario mensual del trabajador seleccionado.</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Salario por hora:"))
        self.salario_hora.setToolTip(_translate("MainWindow", "<html><head/><body><p>Muestra el salario por hora del trabajador seleccionado.</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cálculos:"))
        self.trabajo_en_descanso.setToolTip(_translate("MainWindow", "<html><head/><body><p>Tildar esta opción en el caso de que la hora extraordinaria haya ocurrido en un periodo de descanso semanal del trabajador.</p></body></html>"))
        self.trabajo_en_descanso.setText(_translate("MainWindow", "Día de descanso del trabajador"))
        self.label_16.setText(_translate("MainWindow", "%"))
        self.label_13.setText(_translate("MainWindow", "Valor"))
        self.label_11.setText(_translate("MainWindow", "Valor"))
        self.label_8.setText(_translate("MainWindow", "Horas extras"))
        self.label_12.setText(_translate("MainWindow", "Horas nocturnas"))
        self.hora_extra_noct.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cantidad de horas extraordinarias a registrar por concepto de horas nocturnas.</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Valor"))
        self.label_9.setText(_translate("MainWindow", "Horas en exceso"))
        self.label_14.setText(_translate("MainWindow", "TOTAL"))
        self.total_he_doble_exceso.setToolTip(_translate("MainWindow", "<html><head/><body><p>Total a pagar por concepto de horas extraordinarias trabajadas en exceso.</p></body></html>"))
        self.total_he_normal.setToolTip(_translate("MainWindow", "<html><head/><body><p>Total a pagar por concepto de horas extraordinarias.</p></body></html>"))
        self.hora_extra.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cantidad de horas extraordinarias a registrar.</p></body></html>"))
        self.hora_extra_doble.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cantidad de horas extraordinarias a registrar por concepto de trabajar más de lo estipuldo por semana, por ejemplo más de 68 horas semanales como especifica el art 203 del CDT Dominicano. </p></body></html>"))
        self.gran_total.setToolTip(_translate("MainWindow", "<html><head/><body><p>Total a recibir por el trabajador.</p></body></html>"))
        self.total_he_nocturno.setToolTip(_translate("MainWindow", "<html><head/><body><p>Total a pagar por concepto de horas extraordinarias trabajadas en horas nocturnas.</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "%"))
        self.label_18.setText(_translate("MainWindow", "%"))
        self.porc_hora_extra.setToolTip(_translate("MainWindow", "<html><head/><body><p>Porcentaje a aplicar a las horas extraoridinarias.</p></body></html>"))
        self.porc_hora_extra_exceso.setToolTip(_translate("MainWindow", "<html><head/><body><p>Porcentaje a aplicar a las horas extraoridinarias por concepto de horas trabajadas más allá del limete semanal. Por ejemplo las 68 horas referetes al artículo 203 del CDT Dominicano.</p></body></html>"))
        self.porc_nocturno.setToolTip(_translate("MainWindow", "<html><head/><body><p>Porcentaje a aplicar a las horas extraoridinarias por concepto de horas nocturnas.</p></body></html>"))
        self.borrar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Borra el registro activo.</p></body></html>"))
        self.borrar.setText(_translate("MainWindow", "Borrar"))
        self.agregar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presione este botón para agregar la variación. Este botón sólo se activa si el TOTAL de horas extras es diferente de cero y si agregó una nota.</p></body></html>"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.cancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Este botón cierra la pantalla actual.</p></body></html>"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


