# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inasis.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.fecha_doc = QtWidgets.QDateEdit(self.frame_2)
        self.fecha_doc.setReadOnly(True)
        self.fecha_doc.setObjectName("fecha_doc")
        self.horizontalLayout_2.addWidget(self.fecha_doc)
        spacerItem = QtWidgets.QSpacerItem(127, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.id_visible = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_visible.sizePolicy().hasHeightForWidth())
        self.id_visible.setSizePolicy(sizePolicy)
        self.id_visible.setMaximumSize(QtCore.QSize(30, 16777215))
        self.id_visible.setReadOnly(True)
        self.id_visible.setObjectName("id_visible")
        self.horizontalLayout_2.addWidget(self.id_visible)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.trabajador = QtWidgets.QComboBox(self.groupBox)
        self.trabajador.setObjectName("trabajador")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trabajador)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.tipoina = QtWidgets.QComboBox(self.groupBox)
        self.tipoina.setObjectName("tipoina")
        self.tipoina.addItem("")
        self.tipoina.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tipoina)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.inasis = QtWidgets.QLineEdit(self.groupBox)
        self.inasis.setReadOnly(True)
        self.inasis.setObjectName("inasis")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.inasis)
        self.fechai = QtWidgets.QDateTimeEdit(self.groupBox)
        self.fechai.setTime(QtCore.QTime(7, 0, 0))
        self.fechai.setMaximumTime(QtCore.QTime(17, 0, 0))
        self.fechai.setMinimumTime(QtCore.QTime(7, 0, 0))
        self.fechai.setCalendarPopup(True)
        self.fechai.setObjectName("fechai")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fechai)
        self.fechaf = QtWidgets.QDateTimeEdit(self.groupBox)
        self.fechaf.setTime(QtCore.QTime(17, 0, 0))
        self.fechaf.setMaximumTime(QtCore.QTime(17, 0, 0))
        self.fechaf.setMinimumTime(QtCore.QTime(11, 0, 0))
        self.fechaf.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.fechaf.setCalendarPopup(True)
        self.fechaf.setObjectName("fechaf")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fechaf)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horas_inasis = QtWidgets.QLineEdit(self.groupBox)
        self.horas_inasis.setObjectName("horas_inasis")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.horas_inasis)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.tota_inasis = QtWidgets.QLineEdit(self.groupBox)
        self.tota_inasis.setReadOnly(True)
        self.tota_inasis.setObjectName("tota_inasis")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.tota_inasis)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.sal_hora = QtWidgets.QLineEdit(self.groupBox)
        self.sal_hora.setReadOnly(True)
        self.sal_hora.setObjectName("sal_hora")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sal_hora)
        self.sal_mensual = QtWidgets.QLineEdit(self.groupBox)
        self.sal_mensual.setReadOnly(True)
        self.sal_mensual.setObjectName("sal_mensual")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sal_mensual)
        self.nota = QtWidgets.QLineEdit(self.groupBox)
        self.nota.setObjectName("nota")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nota)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.borrar = QtWidgets.QPushButton(self.frame)
        self.borrar.setObjectName("borrar")
        self.horizontalLayout.addWidget(self.borrar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout.addWidget(self.agregar)
        spacerItem3 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem4 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fecha_doc, self.id_visible)
        MainWindow.setTabOrder(self.id_visible, self.trabajador)
        MainWindow.setTabOrder(self.trabajador, self.sal_mensual)
        MainWindow.setTabOrder(self.sal_mensual, self.sal_hora)
        MainWindow.setTabOrder(self.sal_hora, self.tipoina)
        MainWindow.setTabOrder(self.tipoina, self.fechai)
        MainWindow.setTabOrder(self.fechai, self.fechaf)
        MainWindow.setTabOrder(self.fechaf, self.nota)
        MainWindow.setTabOrder(self.nota, self.inasis)
        MainWindow.setTabOrder(self.inasis, self.horas_inasis)
        MainWindow.setTabOrder(self.horas_inasis, self.tota_inasis)
        MainWindow.setTabOrder(self.tota_inasis, self.borrar)
        MainWindow.setTabOrder(self.borrar, self.agregar)
        MainWindow.setTabOrder(self.agregar, self.cancelar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro de inasistencia"))
        self.label_8.setText(_translate("MainWindow", "Fecha de documento: "))
        self.fecha_doc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Fecha en la que se hace el registro.</p></body></html>"))
        self.fecha_doc.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.label_9.setText(_translate("MainWindow", "ID:"))
        self.id_visible.setToolTip(_translate("MainWindow", "<html><head/><body><p>ID del registro.</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Datos de la inasistencia:"))
        self.label.setText(_translate("MainWindow", "Trabajador:"))
        self.trabajador.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione de este listado al trabajador que le quiera registrar la variación</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Tipo de falta:"))
        self.tipoina.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione el tipo de falta del trabajador. Si selecciona Injustificada las horas de falta serán descontadas al trabajador en la proxima corrida de nómina. Si seleccoina justificada las horas de falta serán computadas como regustro en la base de datos pero no serán descontadas al trabajador.</p></body></html>"))
        self.tipoina.setItemText(0, _translate("MainWindow", "Justificada"))
        self.tipoina.setItemText(1, _translate("MainWindow", "Injustificada"))
        self.label_3.setText(_translate("MainWindow", "Fecha inicial:"))
        self.label_4.setText(_translate("MainWindow", "Fecha final:"))
        self.label_6.setText(_translate("MainWindow", "Nota:"))
        self.label_7.setText(_translate("MainWindow", "Dias de faltas:"))
        self.inasis.setToolTip(_translate("MainWindow", "<html><head/><body><p>Este campo muestra el resultado del cálculo de la variación en días.</p></body></html>"))
        self.fechai.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indique la fecha y la hora de inicio de la falta.</p></body></html>"))
        self.fechai.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy hh:mm"))
        self.fechaf.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indique la fecha y la hora final de la falta</p></body></html>"))
        self.fechaf.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy hh:mm"))
        self.label_5.setText(_translate("MainWindow", "Equivalente en Horas:"))
        self.horas_inasis.setToolTip(_translate("MainWindow", "<html><head/><body><p>Este campo muestra el resultado del cálculo de la variación en horas.</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Monto (DOP):"))
        self.tota_inasis.setToolTip(_translate("MainWindow", "<html><head/><body><p>Monto total a ser desconado al trabajador en la siguiente nómina.</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Salario mensual:"))
        self.label_12.setText(_translate("MainWindow", "Salario por hora:"))
        self.sal_hora.setToolTip(_translate("MainWindow", "<html><head/><body><p>Salario por hora</p></body></html>"))
        self.sal_mensual.setToolTip(_translate("MainWindow", "<html><head/><body><p>Salario mensual del trabajador</p></body></html>"))
        self.nota.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indique una nota relativa a esta variación. OBLIGATORIO.</p></body></html>"))
        self.borrar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Borra el registro activo.</p></body></html>"))
        self.borrar.setText(_translate("MainWindow", "Borrar"))
        self.agregar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presione este botón para agregar la variación. Este botón sólo se activa si el calculo de horas extras es diferente de cero y si agregó una nota.</p></body></html>"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.cancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Este botón cierra la pantalla actual.</p></body></html>"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


