# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_empresa.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 761, 405))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nombre = QtWidgets.QLineEdit(self.groupBox_2)
        self.nombre.setObjectName("nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nombre)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.direccion = QtWidgets.QLineEdit(self.groupBox_2)
        self.direccion.setObjectName("direccion")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.direccion)
        self.ciudad = QtWidgets.QLineEdit(self.groupBox_2)
        self.ciudad.setObjectName("ciudad")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ciudad)
        self.estado = QtWidgets.QLineEdit(self.groupBox_2)
        self.estado.setObjectName("estado")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.estado)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.pais = QtWidgets.QLineEdit(self.groupBox_2)
        self.pais.setObjectName("pais")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pais)
        self.tel_fijo = QtWidgets.QLineEdit(self.groupBox_2)
        self.tel_fijo.setObjectName("tel_fijo")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tel_fijo)
        self.tel_cel = QtWidgets.QLineEdit(self.groupBox_2)
        self.tel_cel.setObjectName("tel_cel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tel_cel)
        self.web = QtWidgets.QLineEdit(self.groupBox_2)
        self.web.setObjectName("web")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.web)
        self.email = QtWidgets.QLineEdit(self.groupBox_2)
        self.email.setObjectName("email")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.email)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.rep_legal = QtWidgets.QLineEdit(self.groupBox_2)
        self.rep_legal.setObjectName("rep_legal")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.rep_legal)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.cierre_fiscal = QtWidgets.QComboBox(self.groupBox_2)
        self.cierre_fiscal.setObjectName("cierre_fiscal")
        self.cierre_fiscal.addItem("")
        self.cierre_fiscal.addItem("")
        self.cierre_fiscal.addItem("")
        self.cierre_fiscal.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.cierre_fiscal)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 2, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.rnc = QtWidgets.QLineEdit(self.groupBox_2)
        self.rnc.setObjectName("rnc")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rnc)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.reg_comercio = QtWidgets.QLineEdit(self.groupBox_2)
        self.reg_comercio.setObjectName("reg_comercio")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.reg_comercio)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.reg_mt = QtWidgets.QLineEdit(self.groupBox_2)
        self.reg_mt.setObjectName("reg_mt")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reg_mt)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.reg_tss = QtWidgets.QLineEdit(self.groupBox_2)
        self.reg_tss.setObjectName("reg_tss")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.reg_tss)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.reg_infotep = QtWidgets.QLineEdit(self.groupBox_2)
        self.reg_infotep.setObjectName("reg_infotep")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.reg_infotep)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.logo_pie = QtWidgets.QLabel(self.groupBox_3)
        self.logo_pie.setText("")
        self.logo_pie.setObjectName("logo_pie")
        self.verticalLayout_6.addWidget(self.logo_pie)
        self.boton_logo_pie = QtWidgets.QPushButton(self.groupBox_3)
        self.boton_logo_pie.setObjectName("boton_logo_pie")
        self.verticalLayout_6.addWidget(self.boton_logo_pie)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.gridLayout.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QLabel(self.groupBox)
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        self.boton_logo = QtWidgets.QPushButton(self.groupBox)
        self.boton_logo.setObjectName("boton_logo")
        self.verticalLayout_2.addWidget(self.boton_logo)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.frame_4, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(124, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.aceptar = QtWidgets.QPushButton(self.frame_2)
        self.aceptar.setObjectName("aceptar")
        self.horizontalLayout_2.addWidget(self.aceptar)
        spacerItem1 = QtWidgets.QSpacerItem(123, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cancelar = QtWidgets.QPushButton(self.frame_2)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout_2.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(124, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.barra = QtWidgets.QStatusBar(MainWindow)
        self.barra.setObjectName("barra")
        MainWindow.setStatusBar(self.barra)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Datos de la sociedad"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Datos de la sociedad:"))
        self.label.setText(_translate("MainWindow", "Nombre de la sociedad:"))
        self.nombre.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coloque el nombre de la sociedad o empresa.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Dirección:"))
        self.label_3.setText(_translate("MainWindow", "Ciudad:"))
        self.label_4.setText(_translate("MainWindow", "Estado o provincia:"))
        self.direccion.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba la calle, avenida y número de la sociedad o empresa.</p></body></html>"))
        self.ciudad.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba la ciudad donde se localiza la empresa o sociedad.</p></body></html>"))
        self.estado.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba la provincia o estado donde se localiza la empresa o sociedad.</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Pais:"))
        self.label_6.setText(_translate("MainWindow", "Teléfono fijo:"))
        self.label_7.setText(_translate("MainWindow", "Teléfono célular:"))
        self.label_8.setText(_translate("MainWindow", "Página web:"))
        self.label_9.setText(_translate("MainWindow", "Correo electrónico:"))
        self.pais.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba el pais donde se localiza la empresa o sociedad.</p></body></html>"))
        self.tel_fijo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba el número telefónico fijo de la empresa o sociedad.</p></body></html>"))
        self.tel_cel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba el número telefónico fijo de la empresa o sociedad.</p></body></html>"))
        self.web.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba la dirección de la página web de la empresa.</p></body></html>"))
        self.email.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba la dirección de correo electrónico de la empresa.</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Representante legal:"))
        self.rep_legal.setToolTip(_translate("MainWindow", "<html><head/><body><p>Indique el nombre del representante legal de la sociedad o empresa.</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Fecha de cierre fiscal:"))
        self.cierre_fiscal.setToolTip(_translate("MainWindow", "<html><head/><body><p>Campo obligatorio. Puede ser editado más adelante.</p><p><span style=\" font-weight:600;\">Personas Jurídicas:</span></p><p>La fecha de cierre de las entidades jurídicas es establecida por el consejo directivo (accionistas) en los estatutos constitutivos de la entidad, observando las disposiciones del Art. 300 el Código Tributario. Las fechas de cierre que la sociedad puede seleccionar son:</p><p>-31 de diciembre</p><p>-31 de marzo</p><p>-30 de junio</p><p>-30 de septiembre.</p><p><span style=\" font-weight:600;\">Personas físicas y Fideicomisos:</span></p><p>La fecha de cierre de las personas físicas y fideicomisos es el 31 de diciembre.</p></body></html>"))
        self.cierre_fiscal.setItemText(0, _translate("MainWindow", "31 DE DICIEMBRE"))
        self.cierre_fiscal.setItemText(1, _translate("MainWindow", "31 DE MARZO"))
        self.cierre_fiscal.setItemText(2, _translate("MainWindow", "30 DE JUNIO"))
        self.cierre_fiscal.setItemText(3, _translate("MainWindow", "30 DE SEPTIEMBRE"))
        self.label_11.setText(_translate("MainWindow", "RNC:"))
        self.rnc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba el número de RNC asignado por la DGII a la empresa. Sólo números consecutivos por favor.</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Registro de Comercio:"))
        self.reg_comercio.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba número de registro de comercio asignado por la Cámara de comercio a la empresa.</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Registro MT:"))
        self.reg_mt.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba el número de identificación asignado por el Ministerio de Trabajo a la empresa.</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Registro TSS:"))
        self.reg_tss.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba el número de identificación asignado por la Tesorería de la Seguridad Social a la empresa.</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Registro INFOTEP"))
        self.reg_infotep.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba el número de identificación asignado por el INFOTEP a la empresa.</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Logo pie de páginas:"))
        self.boton_logo_pie.setToolTip(_translate("MainWindow", "<html><head/><body><p>Precione este botón para cambiar el logo de pie de página de la empresa. Éste logo será el que parecerá en los documentos que usen logo de pie de página, como por ejemplo las cartas de trabajo.</p></body></html>"))
        self.boton_logo_pie.setText(_translate("MainWindow", "Actualizar"))
        self.groupBox.setTitle(_translate("MainWindow", "Logo de la empresa:"))
        self.boton_logo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Precione este botón para cambiar el logo de la empresa. Éste logo será el que parecerá en los recibos o volantes de pago.</p></body></html>"))
        self.boton_logo.setText(_translate("MainWindow", "Actualizar"))
        self.aceptar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Precione Aceptar para proceder con los cambios.</p></body></html>"))
        self.aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.cancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Precione Cancelar para descartar los cambios.</p></body></html>"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


