# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_list_usu(object):
    def setupUi(self, list_usu):
        list_usu.setObjectName("list_usu")
        list_usu.setWindowModality(QtCore.Qt.WindowModal)
        list_usu.resize(377, 327)
        self.centralwidget = QtWidgets.QWidget(list_usu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verFicha = QtWidgets.QPushButton(self.frame)
        self.verFicha.setObjectName("verFicha")
        self.horizontalLayout.addWidget(self.verFicha)
        spacerItem1 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.borrar = QtWidgets.QPushButton(self.frame)
        self.borrar.setObjectName("borrar")
        self.horizontalLayout.addWidget(self.borrar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.crear = QtWidgets.QPushButton(self.frame)
        self.crear.setObjectName("crear")
        self.horizontalLayout.addWidget(self.crear)
        spacerItem3 = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cerrar = QtWidgets.QPushButton(self.frame)
        self.cerrar.setObjectName("cerrar")
        self.horizontalLayout.addWidget(self.cerrar)
        spacerItem4 = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame)
        list_usu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(list_usu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 18))
        self.menubar.setObjectName("menubar")
        list_usu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(list_usu)
        self.statusbar.setObjectName("statusbar")
        list_usu.setStatusBar(self.statusbar)

        self.retranslateUi(list_usu)
        QtCore.QMetaObject.connectSlotsByName(list_usu)

    def retranslateUi(self, list_usu):
        _translate = QtCore.QCoreApplication.translate
        list_usu.setWindowTitle(_translate("list_usu", "Listado de usuarios"))
        self.label.setText(_translate("list_usu", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Listado de Usuarios</span></p></body></html>"))
        self.tableWidget.setToolTip(_translate("list_usu", "<html><head/><body><p>Dar click sobre un usuario y presione el botón &quot;Ver datos&quot; para ver su información, o tambien dar doble click sobre la fila.</p></body></html>"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("list_usu", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("list_usu", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("list_usu", "Usuario"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("list_usu", "Accesos"))
        self.verFicha.setText(_translate("list_usu", "Ver datos"))
        self.borrar.setText(_translate("list_usu", "Borrar"))
        self.crear.setToolTip(_translate("list_usu", "<html><head/><body><p>Crear nuevo trabajador</p></body></html>"))
        self.crear.setText(_translate("list_usu", "Crear Nuevo"))
        self.cerrar.setText(_translate("list_usu", "Cerrar"))
