# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prestamos.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabla_prestamos = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_prestamos.setObjectName("tabla_prestamos")
        self.tabla_prestamos.setColumnCount(10)
        self.tabla_prestamos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_prestamos.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.tabla_prestamos)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tabla_detalles = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_detalles.setObjectName("tabla_detalles")
        self.tabla_detalles.setColumnCount(3)
        self.tabla_detalles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_detalles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_detalles.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_detalles.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tabla_detalles)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout.addWidget(self.agregar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.imprimir = QtWidgets.QPushButton(self.frame)
        self.imprimir.setObjectName("imprimir")
        self.horizontalLayout.addWidget(self.imprimir)
        spacerItem2 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.borrar = QtWidgets.QPushButton(self.frame)
        self.borrar.setObjectName("borrar")
        self.horizontalLayout.addWidget(self.borrar)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prestamos/adelantos"))
        self.tabla_prestamos.setToolTip(_translate("MainWindow", "<html><head/><body><p>El estatus &quot;ABIERTO&quot; significa que el crédito no ha sido abonado al trabajador, por lo tanto el mismo puede ser borrado haciendo click sobre la línea del crédito y luego presionando el botón &quot;Borrar&quot;. El estatus &quot;PENDIENTE&quot;, significa que el crédito fue abonado al trabajador y ahora debe ser cobrado. El estatus &quot;PAGADO&quot; significa que el trabajador ha pagado todas las cuotas del crédito.</p><p><br/></p><p><br/></p></body></html>"))
        self.tabla_prestamos.setSortingEnabled(True)
        item = self.tabla_prestamos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id_prestamo"))
        item = self.tabla_prestamos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Trabajador"))
        item = self.tabla_prestamos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tabla_prestamos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Monto"))
        item = self.tabla_prestamos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cuotas"))
        item = self.tabla_prestamos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Monto Cuota"))
        item = self.tabla_prestamos.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Estatus"))
        item = self.tabla_prestamos.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cuotas Pendientes"))
        item = self.tabla_prestamos.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Monto Pendiente"))
        item = self.tabla_prestamos.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Nota"))
        self.tabla_detalles.setToolTip(_translate("MainWindow", "<html><head/><body><p>Muestra un detalle de cada couta del prestamos seleecionado en la tabla de arriba.</p></body></html>"))
        item = self.tabla_detalles.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id_cuota"))
        item = self.tabla_detalles.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Periodo"))
        item = self.tabla_detalles.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Estatus"))
        self.agregar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presionar para registrar un préstamo a un trabajador.</p></body></html>"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.imprimir.setToolTip(_translate("MainWindow", "<html><head/><body><p>Imprime el contrato del préstamo que esté seleccionado.</p></body></html>"))
        self.imprimir.setText(_translate("MainWindow", "Imprimir"))
        self.borrar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Borra el préstamo que esté seleccionado siempre y cuando el mismo tenga un estatus &quot;ABIERTO&quot;</p></body></html>"))
        self.borrar.setText(_translate("MainWindow", "Borrar"))
        self.cancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cierra la ventana actual.</p></body></html>"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


