# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primerPeriodo.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pPeriodo(object):
    def setupUi(self, pPeriodo):
        pPeriodo.setObjectName("pPeriodo")
        pPeriodo.setWindowModality(QtCore.Qt.WindowModal)
        pPeriodo.resize(247, 289)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pPeriodo.sizePolicy().hasHeightForWidth())
        pPeriodo.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(pPeriodo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pplabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pplabel.sizePolicy().hasHeightForWidth())
        self.pplabel.setSizePolicy(sizePolicy)
        self.pplabel.setObjectName("pplabel")
        self.verticalLayout.addWidget(self.pplabel)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ppdateEdit = QtWidgets.QDateEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppdateEdit.sizePolicy().hasHeightForWidth())
        self.ppdateEdit.setSizePolicy(sizePolicy)
        self.ppdateEdit.setCalendarPopup(True)
        self.ppdateEdit.setObjectName("ppdateEdit")
        self.horizontalLayout.addWidget(self.ppdateEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.ppaceptar = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppaceptar.sizePolicy().hasHeightForWidth())
        self.ppaceptar.setSizePolicy(sizePolicy)
        self.ppaceptar.setObjectName("ppaceptar")
        self.horizontalLayout_2.addWidget(self.ppaceptar)
        spacerItem3 = QtWidgets.QSpacerItem(19, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.ppcancelar = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppcancelar.sizePolicy().hasHeightForWidth())
        self.ppcancelar.setSizePolicy(sizePolicy)
        self.ppcancelar.setObjectName("ppcancelar")
        self.horizontalLayout_2.addWidget(self.ppcancelar)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame)
        pPeriodo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pPeriodo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 247, 18))
        self.menubar.setObjectName("menubar")
        pPeriodo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pPeriodo)
        self.statusbar.setObjectName("statusbar")
        pPeriodo.setStatusBar(self.statusbar)

        self.retranslateUi(pPeriodo)
        QtCore.QMetaObject.connectSlotsByName(pPeriodo)

    def retranslateUi(self, pPeriodo):
        _translate = QtCore.QCoreApplication.translate
        pPeriodo.setWindowTitle(_translate("pPeriodo", "Primer Periodo"))
        self.pplabel.setText(_translate("pPeriodo", "<html><head/><body><p><span style=\" font-weight:600;\">Fecha de inicio del primer periodo</span></p></body></html>"))
        self.ppdateEdit.setToolTip(_translate("pPeriodo", "<html><head/><body><p>Introducir la fecha de inicio del primer periodo de la empresa. La empresa maneja periodos quincenales, por lo tanto para la primera quincena indique el día 1 del mes y para la segunda quincena indique el día 15 del mes.</p></body></html>"))
        self.ppdateEdit.setDisplayFormat(_translate("pPeriodo", "dd-MM-yyyy"))
        self.ppaceptar.setText(_translate("pPeriodo", "Aceptar"))
        self.ppcancelar.setText(_translate("pPeriodo", "Cancelar"))


