# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro_prestamo.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(262, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.trabajador = QtWidgets.QComboBox(self.groupBox)
        self.trabajador.setObjectName("trabajador")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trabajador)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.monto = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.monto.setMinimum(1.0)
        self.monto.setMaximum(999999.99)
        self.monto.setObjectName("monto")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.monto)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cuotas = QtWidgets.QSpinBox(self.groupBox)
        self.cuotas.setMinimum(1)
        self.cuotas.setMaximum(48)
        self.cuotas.setObjectName("cuotas")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cuotas)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.monto_cuotas = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.monto_cuotas.setReadOnly(True)
        self.monto_cuotas.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monto_cuotas.setDecimals(4)
        self.monto_cuotas.setMaximum(99999999.99)
        self.monto_cuotas.setProperty("value", 1.0)
        self.monto_cuotas.setObjectName("monto_cuotas")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.monto_cuotas)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.nota = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nota.sizePolicy().hasHeightForWidth())
        self.nota.setSizePolicy(sizePolicy)
        self.nota.setObjectName("nota")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nota)
        self.imprimir = QtWidgets.QCheckBox(self.groupBox)
        self.imprimir.setObjectName("imprimir")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.imprimir)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout.addWidget(self.agregar)
        spacerItem1 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 262, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro de préstamo/adelanto"))
        self.groupBox.setTitle(_translate("MainWindow", "Registro de préstamo/adelanto:"))
        self.label.setText(_translate("MainWindow", "Trabajador:"))
        self.trabajador.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione de este listado al trabajador que le quiera registrar el préstamo o adelanto.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Monto (DOP):"))
        self.monto.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ingrese el monto, en pesos, del préstamo o adelanto.</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Cuotas:"))
        self.cuotas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cantidad de quincenas para que el trabajador pague el préstamo.</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Monto de las cuotas:"))
        self.monto_cuotas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Monto a descontar a cada trabajador por quincena, es el resultado de dividir el monto del préstamo entre el número de quincenas del crédito.</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Nota:"))
        self.nota.setToolTip(_translate("MainWindow", "<html><head/><body><p>Es obligartorio para agregar el préstamo que realice una nota.</p></body></html>"))
        self.imprimir.setText(_translate("MainWindow", "Imprimir contrato"))
        self.agregar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presione este botón para agregar la variación. Este botón sólo se activa si el calculo de horas extras es diferente de cero y si agregó una nota.</p></body></html>"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.cancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Este botón cierra la pantalla actual.</p></body></html>"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


