# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sal_min.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sal_min(object):
    def setupUi(self, sal_min):
        sal_min.setObjectName("sal_min")
        sal_min.setWindowModality(QtCore.Qt.WindowModal)
        sal_min.resize(346, 214)
        self.centralwidget = QtWidgets.QWidget(sal_min)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setMaximum(9999999999.99)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.guardar = QtWidgets.QPushButton(self.frame)
        self.guardar.setObjectName("guardar")
        self.horizontalLayout.addWidget(self.guardar)
        spacerItem1 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame)
        sal_min.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sal_min)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 18))
        self.menubar.setObjectName("menubar")
        sal_min.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sal_min)
        self.statusbar.setObjectName("statusbar")
        sal_min.setStatusBar(self.statusbar)

        self.retranslateUi(sal_min)
        QtCore.QMetaObject.connectSlotsByName(sal_min)
        sal_min.setTabOrder(self.dateEdit, self.doubleSpinBox)
        sal_min.setTabOrder(self.doubleSpinBox, self.textEdit)
        sal_min.setTabOrder(self.textEdit, self.guardar)
        sal_min.setTabOrder(self.guardar, self.cancelar)

    def retranslateUi(self, sal_min):
        _translate = QtCore.QCoreApplication.translate
        sal_min.setWindowTitle(_translate("sal_min", "Salario mínimo"))
        self.label_4.setText(_translate("sal_min", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Definición de salario mínimo:</span></p></body></html>"))
        self.label_3.setText(_translate("sal_min", "Nota:"))
        self.doubleSpinBox.setToolTip(_translate("sal_min", "<html><head/><body><p>Colocar valor en pesos dominicanos del nuevo salario mínimo. Usualmente este valor es igual al promedio aritmetico entre los salarios minimos en las escalas del salario mínimo no sectorial. </p></body></html>"))
        self.textEdit.setToolTip(_translate("sal_min", "<html><head/><body><p>Coloque aquí cualquier información de interés relacionada con el salario mínimo nacional.</p></body></html>"))
        self.dateEdit.setToolTip(_translate("sal_min", "<html><head/><body><p>Coloque aquí la fecha de entrada en vigencia del nuevo salario mínimo nacional.</p></body></html>"))
        self.dateEdit.setDisplayFormat(_translate("sal_min", "dd-MM-yyyy"))
        self.label.setText(_translate("sal_min", "Fecha de inicio de vigencia del salario:"))
        self.label_2.setText(_translate("sal_min", "Valor en DOP del salario:"))
        self.guardar.setToolTip(_translate("sal_min", "<html><head/><body><p>Al presionar aquí se guardarán los cambios realizados.</p></body></html>"))
        self.guardar.setText(_translate("sal_min", "Guardar"))
        self.cancelar.setText(_translate("sal_min", "Cancelar"))
