# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'salario_nuevo.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(259, 258)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.trabajador = QtWidgets.QComboBox(self.groupBox)
        self.trabajador.setObjectName("trabajador")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trabajador)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fecha = QtWidgets.QDateEdit(self.groupBox)
        self.fecha.setCalendarPopup(True)
        self.fecha.setObjectName("fecha")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fecha)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.nota = QtWidgets.QPlainTextEdit(self.groupBox)
        self.nota.setObjectName("nota")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nota)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.salario = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.salario.setMaximum(99999999.99)
        self.salario.setObjectName("salario")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.salario)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.salario_actual = QtWidgets.QLineEdit(self.groupBox)
        self.salario_actual.setReadOnly(True)
        self.salario_actual.setObjectName("salario_actual")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.salario_actual)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.agregar = QtWidgets.QPushButton(self.frame)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout.addWidget(self.agregar)
        spacerItem1 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelar = QtWidgets.QPushButton(self.frame)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 259, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro salario nuevo"))
        self.groupBox.setTitle(_translate("MainWindow", "Registro de salario nuevo:"))
        self.label.setText(_translate("MainWindow", "Trabajador:"))
        self.trabajador.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione de este listado al trabajador activo al que le quiera registrar la variación</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Fecha:"))
        self.fecha.setToolTip(_translate("MainWindow", "<html><head/><body><p>Seleccione la fecha donde ocurrio la variación.</p></body></html>"))
        self.fecha.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.label_6.setText(_translate("MainWindow", "Nota:"))
        self.nota.setToolTip(_translate("MainWindow", "<html><head/><body><p>Es obligartorio para agregar la variación que realice una nota.</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Salario nuevo:"))
        self.salario.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coloque el valor mensual del salario nuevo.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Salario actual:"))
        self.agregar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presione este botón para agregar la variación. Este botón sólo se activa si el calculo de horas extras es diferente de cero y si agregó una nota.</p></body></html>"))
        self.agregar.setText(_translate("MainWindow", "Agregar"))
        self.cancelar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Este botón cierra la pantalla actual.</p></body></html>"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))


