# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vacaciones2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vacaciones(object):
    def setupUi(self, vacaciones):
        vacaciones.setObjectName("vacaciones")
        vacaciones.setWindowModality(QtCore.Qt.WindowModal)
        vacaciones.resize(578, 356)
        self.centralwidget = QtWidgets.QWidget(vacaciones)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cerrar = QtWidgets.QPushButton(self.frame)
        self.cerrar.setObjectName("cerrar")
        self.horizontalLayout.addWidget(self.cerrar)
        spacerItem2 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.siete_dias = QtWidgets.QRadioButton(self.frame_5)
        self.siete_dias.setObjectName("siete_dias")
        self.verticalLayout_4.addWidget(self.siete_dias)
        self.catorce_dias = QtWidgets.QRadioButton(self.frame_5)
        self.catorce_dias.setObjectName("catorce_dias")
        self.verticalLayout_4.addWidget(self.catorce_dias)
        self.otro = QtWidgets.QRadioButton(self.frame_5)
        self.otro.setObjectName("otro")
        self.verticalLayout_4.addWidget(self.otro)
        self.otro_dias = QtWidgets.QSpinBox(self.frame_5)
        self.otro_dias.setMinimum(1)
        self.otro_dias.setObjectName("otro_dias")
        self.verticalLayout_4.addWidget(self.otro_dias)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_5)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2018, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_4.addWidget(self.dateEdit)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.line_2 = QtWidgets.QFrame(self.frame_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.el_dia = QtWidgets.QRadioButton(self.frame_8)
        self.el_dia.setObjectName("el_dia")
        self.verticalLayout.addWidget(self.el_dia)
        self.medio_dia = QtWidgets.QRadioButton(self.frame_8)
        self.medio_dia.setObjectName("medio_dia")
        self.verticalLayout.addWidget(self.medio_dia)
        self.no_contar = QtWidgets.QRadioButton(self.frame_8)
        self.no_contar.setObjectName("no_contar")
        self.verticalLayout.addWidget(self.no_contar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.line_6 = QtWidgets.QFrame(self.frame_6)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.line_5 = QtWidgets.QFrame(self.frame_6)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.trabajadores = QtWidgets.QListWidget(self.frame_7)
        self.trabajadores.setObjectName("trabajadores")
        self.verticalLayout_6.addWidget(self.trabajadores)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.line_4 = QtWidgets.QFrame(self.frame_6)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.line_3 = QtWidgets.QFrame(self.frame_6)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.nota = QtWidgets.QLineEdit(self.frame_3)
        self.nota.setObjectName("nota")
        self.verticalLayout_2.addWidget(self.nota)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.cancelar = QtWidgets.QPushButton(self.frame_2)
        self.cancelar.setObjectName("cancelar")
        self.horizontalLayout_3.addWidget(self.cancelar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.agregar = QtWidgets.QPushButton(self.frame_2)
        self.agregar.setObjectName("agregar")
        self.horizontalLayout_3.addWidget(self.agregar)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_5.addWidget(self.frame_2)
        vacaciones.setCentralWidget(self.centralwidget)

        self.retranslateUi(vacaciones)
        QtCore.QMetaObject.connectSlotsByName(vacaciones)

    def retranslateUi(self, vacaciones):
        _translate = QtCore.QCoreApplication.translate
        vacaciones.setWindowTitle(_translate("vacaciones", "Vacaciones"))
        self.tableWidget.setToolTip(_translate("vacaciones", "<html><head/><body><p>En esta tabla se muestran los peridos vacacionales creados. Se muestran los periodos abiertos y los cerrados o procesados.  Solo se pueden borrar periodos vacacionales abiertos. Para borrar un perido abierto haga click con el ratón en el ID del perido.</p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("vacaciones", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("vacaciones", "Fecha de inicio"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("vacaciones", "Lista de días"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("vacaciones", "Cant de días"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("vacaciones", "Estatus"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("vacaciones", "Nota"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("vacaciones", "Trabajadores"))
        self.checkBox.setToolTip(_translate("vacaciones", "<html><head/><body><p>Tildar este cuadro para poder agregar un nuevo periodo vacacional. Antes de incluir un nuevo periodo vacacional primero debe haber cargado los días feriados del año en el cual pretende crear el perido vacacional.</p></body></html>"))
        self.checkBox.setText(_translate("vacaciones", "Agregar nuevo periodo vacacional:"))
        self.cerrar.setToolTip(_translate("vacaciones", "<html><head/><body><p>Cerrar la ventana.</p></body></html>"))
        self.cerrar.setText(_translate("vacaciones", "Cerrar"))
        self.label.setText(_translate("vacaciones", "Cantidad de días:"))
        self.siete_dias.setText(_translate("vacaciones", "7 días"))
        self.catorce_dias.setText(_translate("vacaciones", "14 días"))
        self.otro.setText(_translate("vacaciones", "Otro:"))
        self.label_2.setText(_translate("vacaciones", "Fecha de inicio:"))
        self.dateEdit.setToolTip(_translate("vacaciones", "<html><head/><body><p>Fecha de inicio del perido vacacional, el cual no debe ser un día domingo o un día feriado.</p></body></html>"))
        self.dateEdit.setDisplayFormat(_translate("vacaciones", "dd-MM-yyyy"))
        self.frame_8.setToolTip(_translate("vacaciones", "<html><head/><body><p>Elija si el sabado debe ser tomado encuenta para el computo de los días de disfrute</p></body></html>"))
        self.label_6.setText(_translate("vacaciones", "Contar sábados?:"))
        self.el_dia.setText(_translate("vacaciones", "El día."))
        self.medio_dia.setText(_translate("vacaciones", "Medio día"))
        self.no_contar.setText(_translate("vacaciones", "No contar"))
        self.label_3.setText(_translate("vacaciones", "Días de vacaciones del periodo:"))
        self.textBrowser.setToolTip(_translate("vacaciones", "<html><head/><body><p>Listado de días de vacaciones. Automaticamente no se incluyen días de descanso o feriados.</p></body></html>"))
        self.label_5.setText(_translate("vacaciones", "Trabajadores:"))
        self.trabajadores.setToolTip(_translate("vacaciones", "<html><head/><body><p>Los trabajadores que aparecen con un fondo rojo tienen menos de un año trabajando en la empresa al momento de iniciar el periodo vacacional seleccionado, por lo tanto, de acuerdo a la ley no les corresponde vacaciones. Igualmente se calculará y pagará sus vacaciones si el trabajador está tildado.</p></body></html>"))
        self.label_4.setText(_translate("vacaciones", "Nota adicional: (opcional)"))
        self.nota.setToolTip(_translate("vacaciones", "<html><head/><body><p>Agregue una nota. Es un campo opcional.</p></body></html>"))
        self.cancelar.setToolTip(_translate("vacaciones", "<html><head/><body><p>Al presionar este botón se cierra la ventana y se pierde la información suministrada.</p></body></html>"))
        self.cancelar.setText(_translate("vacaciones", "Cancelar"))
        self.agregar.setToolTip(_translate("vacaciones", "<html><head/><body><p>Al  hacer click en este botón se agrega el perido vacacional.</p></body></html>"))
        self.agregar.setText(_translate("vacaciones", "Agregar"))


